### ISSUE TITLE
running App in Android Studio gives strange simulator Error

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/AmiKo-Android#12]
I am starting AmiKo-Android in Android-Studio 3.2.1 for Mac with the the following simulators:

 Nexus_5X_API_28_x86
 Pixel_2_API_28

and I always get the following error:
```
12-12 11:59:45.972  2786  5310 I FontsPackageChangeOp: Package com.ywesee.amiko.de has no metadata
12-12 11:59:45.974  5429  5429 W ywesee.amiko.d: Unexpected CPU variant for X86 using defaults: x86
12-12 11:59:46.068  5429  5429 I ywesee.amiko.d: The ClassLoaderContext is a special shared library.
12-12 11:59:46.161  5429  5429 W ywesee.amiko.d: JIT profile information will not be recorded: profile file does not exits.
12-12 11:59:46.164  5429  5429 I chatty  : uid=10085(com.ywesee.amiko.de) identical 10 lines
12-12 11:59:46.164  5429  5429 W ywesee.amiko.d: JIT profile information will not be recorded: profile file does not exits.
12-12 11:59:46.418  5429  5460 D DataBaseHelper: Copying file amiko_db_full_idx_de.db to /data/user/0/com.ywesee.amiko.de/databases/
12-12 11:59:46.513  5429  5460 E AndroidRuntime: Process: com.ywesee.amiko.de, PID: 5429
12-12 11:59:46.513  5429  5460 E AndroidRuntime: 	at com.ywesee.amiko.DataBaseHelper.copyFilesFromNonPersistentFolder(DataBaseHelper.java:136)
12-12 11:59:46.513  5429  5460 E AndroidRuntime: 	at com.ywesee.amiko.DBAdapter.create(DBAdapter.java:193)
12-12 11:59:46.513  5429  5460 E AndroidRuntime: 	at com.ywesee.amiko.MainActivity$AsyncLoadDBTask.doInBackground(MainActivity.java:1085)
12-12 11:59:46.513  5429  5460 E AndroidRuntime: 	at com.ywesee.amiko.MainActivity$AsyncLoadDBTask.doInBackground(MainActivity.java:1061)
12-12 11:59:46.514  5429  5429 I System.out: Found application data folder is in /data/user/0/com.ywesee.amiko.de/files
12-12 11:59:46.539  1868  1918 W ActivityManager: Receiver with filter android.content.IntentFilter@80adc77 already registered for pid 5429, callerPackage is com.ywesee.amiko.de
12-12 11:59:46.552  1868  2639 W ActivityManager:   Force finishing activity com.ywesee.amiko.de/com.ywesee.amiko.MainActivity
12-12 11:59:46.572  1868  1883 I ActivityManager: Showing crash dialog for package com.ywesee.amiko.de u0
12-12 11:59:46.668  2644  4770 W ziparchive: Unable to open '/data/app/com.ywesee.amiko.de-4U8cXBJzSPZMF8IA_TRAyQ==/base.apk': No such file or directory
12-12 11:59:46.668  2644  4770 E s.nexuslaunche: Failed to open APK '/data/app/com.ywesee.amiko.de-4U8cXBJzSPZMF8IA_TRAyQ==/base.apk' I/O error
12-12 11:59:46.669  2644  4770 E ResourcesManager: failed to add asset path /data/app/com.ywesee.amiko.de-4U8cXBJzSPZMF8IA_TRAyQ==/base.apk
12-12 11:59:46.669  2644  4770 W PackageManager: Failure retrieving resources for com.ywesee.amiko.de
12-12 11:59:46.806  1712  1712 D SurfaceFlinger: duplicate layer name: changing com.ywesee.amiko.de/com.ywesee.amiko.MainActivity to com.ywesee.amiko.de/com.ywesee.amiko.MainActivity#1
```

**Comment by zdavatz** [comment]
no database was in the assets folder!
