### ISSUE TITLE
Update to `openjdk 17.0.5 2022-10-18`

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/AmiKo-Android#211]
Google Play says we need to Update to API Level 31:

_Wir haben festgestellt, dass deine App auf eine alte Android-Version ausgerichtet ist. Wir möchten unseren Nutzern eine möglichst sichere Umgebung bieten. Aus diesem Grund müssen alle Apps bei Google Play die Anforderungen an das Ziel-API-Level erfüllen.

Ab dem 31. August 2023 sind Apps, die nicht auf ein API-Level ausgerichtet sind, das maximal zwei Jahre hinter der neuesten Android-Version zurückliegt, nicht für neue Nutzer verfügbar, die Geräte mit Android-Versionen nutzen, die neuer als das Ziel-API-Level deiner App sind.

Aktualisiere deine App auf Android 12 (API-Level 31), damit sie auch für neue Nutzer verfügbar ist._

**Comment by zdavatz** [comment]
Build Error:
```
Starting a Gradle Daemon (subsequent builds will be faster)
java.lang.NoClassDefFoundError: Could not initialize class org.codehaus.groovy.vmplugin.v7.Java7
        at org.codehaus.groovy.vmplugin.VMPluginFactory.<clinit>(VMPluginFactory.java:43)
        at org.codehaus.groovy.reflection.GroovyClassValueFactory.<clinit>(GroovyClassValueFactory.java:35)
        at org.codehaus.groovy.reflection.ClassInfo.<clinit>(ClassInfo.java:107)
        at org.codehaus.groovy.reflection.ReflectionCache.getCachedClass(ReflectionCache.java:95)
        at org.codehaus.groovy.reflection.ReflectionCache.<clinit>(ReflectionCache.java:39)
        at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.registerMethods(MetaClassRegistryImpl.java:210)
        at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.<init>(MetaClassRegistryImpl.java:108)
        at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.<init>(MetaClassRegistryImpl.java:86)
        at groovy.lang.GroovySystem.<clinit>(GroovySystem.java:36)
        at org.codehaus.groovy.runtime.InvokerHelper.<clinit>(InvokerHelper.java:86)
        at groovy.lang.GroovyObjectSupport.getDefaultMetaClass(GroovyObjectSupport.java:59)
        at groovy.lang.GroovyObjectSupport.<init>(GroovyObjectSupport.java:32)
        at org.gradle.internal.extensibility.DefaultExtraPropertiesExtension.<init>(DefaultExtraPropertiesExtension.java:29)
        at org.gradle.internal.extensibility.DefaultConvention.<init>(DefaultConvention.java:49)
        at org.gradle.internal.extensibility.ExtensibleDynamicObject.<init>(ExtensibleDynamicObject.java:60)
        at org.gradle.internal.instantiation.generator.MixInExtensibleDynamicObject.<init>(MixInExtensibleDynamicObject.java:35)
        at org.gradle.initialization.DefaultSettings_Decorated.getAsDynamicObject(Unknown Source)
        at org.gradle.initialization.SettingsFactory.createSettings(SettingsFactory.java:58)
```

**Comment by zdavatz** [comment]
Ich verwende: openjdk 17.0.5 2022-10-18

**Comment by zdavatz** [comment]
1. Ok ich habe das gemacht: `https://stackoverflow.com/questions/35000729/android-studio-could-not-initialize-class-org-codehaus-groovy-runtime-invokerhel/62027565#62027565`
2. jetzt kommt:
```
* What went wrong:
Could not compile build file '/home/zeno/.software/AmiKo-Android/build.gradle'.
> startup failed:
  General error during semantic analysis: Unsupported class file major version 61
  
  java.lang.IllegalArgumentException: Unsupported class file major version 61
        at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:196)
        at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:177)
        at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:163)
        at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:284)
        at org.codehaus.groovy.ast.decompiled.AsmDecompiler.parseClass(AsmDecompiler.java:81)
        at org.codehaus.groovy.control.ClassNodeResolver.findDecompiled(ClassNodeResolver.java:251)
        at org.codehaus.groovy.control.ClassNodeResolver.tryAsLoaderClassOrScript(ClassNodeResolver.java:189)
        at org.codehaus.groovy.control.ClassNodeResolver.findClassNode(ClassNodeResolver.java:169)
        at org.codehaus.groovy.control.ClassNodeResolver.resolveName(ClassNodeResolver.java:125)
        at org.codehaus.groovy.ast.decompiled.AsmReferenceResolver.resolveClassNullable(AsmReferenceResolver.java:57)
        at org.codehaus.groovy.ast.decompiled.AsmReferenceResolver.resolveClass(AsmReferenceResolver.java:44)
        at org.codehaus.groovy.ast.decompiled.AsmReferenceResolver.resolveNonArrayType(AsmReferenceResolver.java:79)
        at org.codehaus.groovy.ast.decompiled.AsmReferenceResolver.resolveType(AsmReferenceResolver.java:70)
        at org.codehaus.groovy.ast.decompiled.MemberSignatureParser.createMethodNode(MemberSignatureParser.java:57)
```

**Comment by zdavatz** [comment]
1. `vim 
2. Das scheint für Java 17 zu klappen: `distributionUrl=https://services.gradle.org/distributions/gradle-7.3-all.zip`
3. Aber dann kommt:
```
FAILURE: Build failed with an exception.

* What went wrong:
Some problems were found with the configuration of task ':downloadAmikoReport' (type 'Download').
  - In plugin 'de.undercouch.download' type 'de.undercouch.gradle.tasks.download.Download' property 'acceptAnyCertificate' is missing an input or output annotation.
    
    Reason: A property without annotation isn't considered during up-to-date checking.
    
    Possible solutions:
      1. Add an input or output annotation.
      2. Mark it as @Internal.
    
    Please refer to https://docs.gradle.org/7.3/userguide/validation_problems.html#missing_annotation for more details about this problem.
  - In plugin 'de.undercouch.download' type 'de.undercouch.gradle.tasks.download.Download' property 'authScheme' is missing an input or output annotation.
    
    Reason: A property without annotation isn't considered during up-to-date checking.
    
    Possible solutions:
      1. Add an input or output annotation.
      2. Mark it as @Internal.
```

**Comment by zdavatz** [comment]
Still getting this error:
<img width="865" alt="Bildschirmfoto 2023-09-23 um 09 17 51" src="https://github.com/zdavatz/AmiKo-Android/assets/4953/a0e85c77-779b-4c0a-8f3f-033a3177315d">

**Comment by zdavatz** [comment]
testing with: `distributionUrl=https\://services.gradle.org/distributions/gradle-8.1.1-bin.zip`

**Comment by zdavatz** [comment]
Trying now: `~/Android/Sdk/cmdline-tools/latest/bin> ./sdkmanager --update`

**Comment by zdavatz** [comment]
I forgot to do git pull ;/
