### ISSUE TITLE
Clicking Update crashes the App

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/AmiKo-Android#5]
1. Install Gradle generated App
2. Click Update in the Menu.
3. App Crashes with the following message in `adb logcat | grep amiko`:
```
12-10 09:06:47.737  8308  8308 D Utilities: File /storage/emulated/0/Download/amiko_db_full_idx_de.zip does not exists. No need to delete.
12-10 09:06:47.740  8308  8308 D Utilities: File /storage/emulated/0/Download/amiko_report_de.html does not exists. No need to delete.
12-10 09:06:47.766   532  3510 W DownloadManager: Path appears to be invalid: /storage/emulated/0/Download/amiko_db_full_idx_de.zip
12-10 09:06:47.770   532  3510 E DatabaseUtils: java.lang.SecurityException: No permission to write to /storage/emulated/0/Download/amiko_db_full_idx_de.zip: Neither user 10161 nor current process has android.permission.WRITE_EXTERNAL_STORAGE.
12-10 09:06:47.774  8308  8308 E AndroidRuntime: Process: com.ywesee.amiko.de, PID: 8308
12-10 09:06:47.774  8308  8308 E AndroidRuntime: java.lang.SecurityException: No permission to write to /storage/emulated/0/Download/amiko_db_full_idx_de.zip: Neither user 10161 nor current process has android.permission.WRITE_EXTERNAL_STORAGE.
12-10 09:06:47.774  8308  8308 E AndroidRuntime:        at com.ywesee.amiko.MainActivity.downloadUpdates(MainActivity.java:1750)
12-10 09:06:47.774  8308  8308 E AndroidRuntime:        at com.ywesee.amiko.MainActivity.onOptionsItemSelected(MainActivity.java:1542)
12-10 09:06:47.779  1580  2330 W ActivityManager:   Force finishing activity com.ywesee.amiko.de/com.ywesee.amiko.MainActivity
12-10 09:06:47.793  1580  1720 I ActivityManager: Showing crash dialog for package com.ywesee.amiko.de u0
12-10 09:06:48.286  1580  1719 W ActivityManager: Activity pause timeout for ActivityRecord{a380997 u0 com.ywesee.amiko.de/com.ywesee.amiko.MainActivity t554 f}
```
4. Seems to be a scecurity issue with writing the downloaded Database file.

**Comment by zdavatz** [comment]
It seems that the File https://github.com/zdavatz/AmiKo-Android/blob/master/AndroidManifest.xml is not yet used to build the new APK, because the permission is in the file: https://github.com/zdavatz/AmiKo-Android/blob/master/AndroidManifest.xml#L13

**Comment by b123400** [comment]
Looking at the App Info screen in the emulator, the app has various permission granted (e.g. Internet and keeping phone awake), Write to external storage however is turned off. I think the manifest is working, it's just the specific permission isn't. Trying this solution https://stackoverflow.com/questions/33162152/storage-permission-error-in-marshmallow
